const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      catgory: "Shirts",
      image: "/images/red.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      desc: "THINGS ALL THE THINGS",
    },
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      catgory: "Shirts",
      image: "/images/blue.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      desc: "THINGS ALL THE THINGS",
    },
    {
      name: "TITS Slim Shirt",
      slug: "nike-slim-shirt",
      catgory: "Shirts",
      image: "/images/gray.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      desc: "THINGS ALL THE THINGS",
    },
    {
      name: "ASSSlim Shirt",
      slug: "nike-slim-shirt",
      catgory: "Shirts",
      image: "/images/.p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      desc: "THINGS ALL THE THINGS",
    },
    {
      name: "BUTTS Slim Shirt",
      slug: "nike-slim-shirt",
      catgory: "Shirts",
      image: "/images/yellow.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      desc: "THINGS ALL THE THINGS",
    },
  ],
};

export default data;
